runtime: nodejs20

automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic

handlers:
  - url: /.*
    secure: always
    script: auto
